# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_2 <- function(y, n, z, mu, gamma, theta, ncol_z) {
    .Call(`_ALR_f_2`, y, n, z, mu, gamma, theta, ncol_z)
}

f_b <- function(nu, mu) {
    .Call(`_ALR_f_b`, nu, mu)
}

f_nu <- function(theta, mu) {
    .Call(`_ALR_f_nu`, theta, mu)
}

mat_inv <- function(a) {
    .Call(`_ALR_mat_inv`, a)
}

mat_3 <- function(a, b, c) {
    .Call(`_ALR_mat_3`, a, b, c)
}

mat_sqr <- function(a) {
    .Call(`_ALR_mat_sqr`, a)
}

